RootManager:

<RootManager@ScreenManager>:
    MainScreen:
        name: "main"
    AuthScreen:
        name: "auth"
    IssuedKeysScreen:
        name: "issued"
    AdminMenuScreen:
        name: "admin_menu"
    AdminPermissionsScreen:
        name: "admin_permissions"
    AdminAddUserScreen:
        name: "admin_add_user"
    AdminAddRoomScreen:
        name: "admin_add_room"
    AdminDeleteUserScreen:
        name: "admin_delete_user"
    AdminDeleteRoomScreen:
        name: "admin_delete_room"
    AdminExportScreen:
        name: "admin_export"
    AdminAssignBoxScreen:
        name: "admin_assign_box"


