from __future__ import annotations

from sqlalchemy import text

from db.session import get_engine


def get_sql_ddl() -> list[str]:
    """Return ordered PostgreSQL DDL statements for all project tables and helpful indexes.

    Notes:
    - Uses IF NOT EXISTS to stay idempotent where supported.
    - Includes safe ADD COLUMN statements for existing databases.
    - Prints each statement before execution for presentation/reporting.
    """
    return [
        # users
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login VARCHAR(64) NOT NULL UNIQUE,
            pin_code VARCHAR(4),
            password_hash VARCHAR(128) NOT NULL,
            phone VARCHAR(32),
            comment VARCHAR(255)
        );
        """,
        # Create index only if it doesn't already exist (even if a unique index exists under a different name)
        """
        DO $$
        BEGIN
            IF to_regclass('public.idx_users_login') IS NULL THEN
                CREATE INDEX idx_users_login ON users(login);
            END IF;
        END $$;
        """,

        # keys
        """
        CREATE TABLE IF NOT EXISTS keys (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(64) NOT NULL UNIQUE,
            description VARCHAR(255),
            pos_x INTEGER,
            pos_y INTEGER
        );
        """,
        """
        DO $$
        BEGIN
            IF to_regclass('public.idx_keys_code') IS NULL THEN
                CREATE INDEX idx_keys_code ON keys(code);
            END IF;
        END $$;
        """,

        # boxes
        """
        CREATE TABLE IF NOT EXISTS boxes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(128) NOT NULL,
            comment VARCHAR(255),
            row INTEGER,
            column INTEGER,
            x INTEGER,
            y INTEGER,
            rooms INTEGER,
            keys_capacity INTEGER,
            key_count INTEGER,
            room_count INTEGER,
            keys_current INTEGER
        );
        """,
        """
        DO $$
        BEGIN
            IF to_regclass('public.idx_boxes_name') IS NULL THEN
                CREATE INDEX idx_boxes_name ON boxes(name);
            END IF;
        END $$;
        """,

        # user_keys
        """
        CREATE TABLE IF NOT EXISTS user_keys (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            key_id INTEGER NOT NULL REFERENCES keys(id) ON DELETE CASCADE
        );
        """,

        # issued_keys
        """
        CREATE TABLE IF NOT EXISTS issued_keys (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            key_id INTEGER NOT NULL UNIQUE REFERENCES keys(id) ON DELETE CASCADE,
            issued_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,

        # key_events
        """
        CREATE TABLE IF NOT EXISTS key_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            key_id INTEGER NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
            action VARCHAR(16) NOT NULL,
            event_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,

        # Backward-compatible alters for existing databases
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(32);",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS comment VARCHAR(255);",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_code VARCHAR(4);",
        "ALTER TABLE issued_keys ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ NOT NULL DEFAULT now();",
        # keys placement in box grid
        "ALTER TABLE keys ADD COLUMN IF NOT EXISTS pos_x INTEGER;",
        "ALTER TABLE keys ADD COLUMN IF NOT EXISTS pos_y INTEGER;",
        # images session metadata and references
        "ALTER TABLE images ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;",
        "ALTER TABLE images ADD COLUMN IF NOT EXISTS box_id INTEGER REFERENCES boxes(id) ON DELETE SET NULL;",
        "ALTER TABLE images ADD COLUMN IF NOT EXISTS session_started_at TIMESTAMPTZ;",
        "ALTER TABLE images ADD COLUMN IF NOT EXISTS session_stopped_at TIMESTAMPTZ;",
        # boxes backward-compatible columns
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS row INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS column INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS x INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS y INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS rooms INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS keys_capacity INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS key_count INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS room_count INTEGER;",
        "ALTER TABLE boxes ADD COLUMN IF NOT EXISTS keys_current INTEGER;",
    ]


def run_sql_ddl() -> None:
    engine = get_engine()
    statements = [s.strip() for s in get_sql_ddl()]
    with engine.begin() as conn:
        for stmt in statements:
            print("\n-- Executing SQL:\n" + stmt)
            conn.execute(text(stmt))


def main() -> int:
    run_sql_ddl()
    print("\nAll DDL statements executed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())



