-- Static PostgreSQL schema for the project (tables and fields)
-- Safe to run on a fresh database. Uses IF NOT EXISTS for idempotency.

BEGIN;

-- users
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(64) NOT NULL UNIQUE,
    pin_code VARCHAR(4),
    password_hash VARCHAR(128) NOT NULL,
    phone VARCHAR(32),
    comment VARCHAR(255)
);

-- keys
CREATE TABLE IF NOT EXISTS keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(255),
    rfid VARCHAR(128),
    pos_x INTEGER,
    pos_y INTEGER
);

-- boxes (конкретный экземпляр аппарата)
CREATE TABLE IF NOT EXISTS boxes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    comment VARCHAR(255),
    row INTEGER,
    column INTEGER,
    -- grid size for tiles
    x INTEGER,
    y INTEGER,
    -- capacity and aggregates
    rooms INTEGER,
    keys_capacity INTEGER,
    key_count INTEGER,
    room_count INTEGER,
    keys_current INTEGER
);

-- Индекс для ускорения поиска по названию бокса
CREATE INDEX IF NOT EXISTS idx_boxes_name ON boxes(name);

-- mapping пользователь ↔ ключ
CREATE TABLE IF NOT EXISTS user_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id INTEGER NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    box_id INTEGER REFERENCES boxes(id) ON DELETE SET NULL
);

-- выданные ключи (каждый ключ может быть выдан только одному пользователю одновременно)
CREATE TABLE IF NOT EXISTS issued_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id INTEGER NOT NULL UNIQUE REFERENCES keys(id) ON DELETE CASCADE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- события по ключам (выдача/возврат)
CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id INTEGER NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    action VARCHAR(16) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- изображения сессий (фото при выдаче/до закрытия сессии)
CREATE TABLE IF NOT EXISTS images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issued_id INTEGER NOT NULL REFERENCES issued_keys(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    box_id INTEGER REFERENCES boxes(id) ON DELETE SET NULL,
    session_started_at TIMESTAMPTZ,
    session_stopped_at TIMESTAMPTZ,
    mime_type VARCHAR(64),
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional backward-compatible ALTERs (no-op on fresh DB)
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS comment VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_code VARCHAR(4);
ALTER TABLE issued_keys ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ NOT NULL DEFAULT now();
-- New columns for keys placement and images session metadata
ALTER TABLE keys ADD COLUMN IF NOT EXISTS pos_x INTEGER;
ALTER TABLE keys ADD COLUMN IF NOT EXISTS pos_y INTEGER;
ALTER TABLE images ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS box_id INTEGER REFERENCES boxes(id) ON DELETE SET NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS session_started_at TIMESTAMPTZ;
ALTER TABLE images ADD COLUMN IF NOT EXISTS session_stopped_at TIMESTAMPTZ;

COMMIT;



